### ISSUE TITLE
little noobish question... how to build this?

### ISSUE THREAD

**Issue by avoidik** [android-ia/hardware_intel_efi_kernelflinger#1]
can you give a hint on this?

**Comment by mihais** [comment]
Please follow the instructions from here: https://01.org/android-ia/user-guides/android-5.x-lollipop-os-build-guide. You have to build the entire Android image for Minnow.

**Comment by avoidik** [comment]
Thank you. Will try.

**Comment by avoidik** [comment]
this manual doesn't cover installer.efi, any hints?
